### ISSUE TITLE
Distillery releases can't find static assets

### ISSUE THREAD

**Issue by dbernheisel** [thoughtbot/brady#17]
When using Brady in production using Distillery releases, it can't find the SVG files as configured.

This is because when using releases, the app gets compiled and the current working directory of the app is no longer the same as it is when in development.

This line: https://github.com/thoughtbot/brady/blob/cc25e57f7a0615ad45da67825524c6dc56d340d0/lib/brady.ex#L35 uses `File.read` which resolves the current directory like this:

```elixir
{:ok, "/var/www/my_app/integration/releases/0.2.0"}
# this directory doesn't have any of the static assets, you'd have to back up a couple levels
```

But the priv folder is far away and in an unpredictable folder.

Instead, it should use `Application.app_dir(:my_app)`, which would resolve to something like this:
```elixir
"/var/www/my_app/integration/releases/0.2.0/lib/my_app-0.2.0"
# this directory has the priv folder.
```

I'm working on a PR to resolve this.

**Comment by johannesE** [comment]
For some reason I still had this issue. Solved it by using this code in the brady file.
```
  defp static_path(file_name) do
    priv_dir = :code.priv_dir(:myapp)
    path = Application.get_env(:myapp, :svg_path) || "static/svg"
    [priv_dir, path, "#{file_name}.svg"] |> Path.join() |> Path.expand
  end
```
and set `config :myapp, svg_path: "static/images/icons/"`
If more people run into this issue, we should take another look at this and maybe use the `:code.priv_dir/1` function instead.
