### ISSUE TITLE
Class names ignore scope

### ISSUE THREAD

**Issue by creuter** [thoughtbot/brady#7]
In my current project, `/dealer/vehicles/103` and `/vehicles/103` have the same class names, despite being scoped differently.

Perhaps the scoped could be prefixed: `dealer-vehicle dealer-vehicle-show`, while the unscoped remains as is: `vehicle vehicle-show`.

**Comment by anellis** [comment]
This has been fixed in 52636ec051d75a32931fba062afb955796da39d6 and released in version 0.0.4
